version: "3.8"

services:
  # Choose Latest MongoDB Database
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 35000:5432

  # The MongoDB Admin tool
  mongo_admin:
    image: mongo-express
    depends_on: 
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 5050:80
